export const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUSTED';
export const FETCH_USERS_LOADED = 'FETCH_USERS_LOADED';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const SORT_USERS = 'SORT_USERS';

export const TOGGLE_DATA_COLLECTION = 'TOGGLE_DATA_COLLECTION';
